//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloTutor
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorsRole
    {
        public System.Guid GUID { get; set; }
        public int TutorId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
